# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
    - nodejs_version: '8'

  DEBUG: phenomic:*

install:
  - choco install yarn
  - yarn --version
  - yarn

test_script:
  - yarn test

cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules -> package.json
  - docs/.screenshots -> docs/content/showcase/entry
  - docs/public/showcase/entry -> docs/content/showcase/entry

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true

init:
  # debugging Appveyor build. More info:
  # https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
