# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: '6'

version: "{build}"
build: off
deploy: off
matrix:
  fast_finish: true

cache:
  - node_modules -> package.json
#   - test-phenomic-theme-base/node_modules -> package.json
#   - docs/node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm set progress=false
  - npm prune
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

# debug
# https://twitter.com/appveyor/status/708038858793836545
# on_finish:
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
